
import javax.swing.JOptionPane;


/**
 *
 * @author axelulises
 */
public class Ventana extends javax.swing.JFrame {
    PrioridadBicola obj;
    
    public Ventana() {
        initComponents();
        setLocationRelativeTo(null);
        String tamano = JOptionPane.showInputDialog(null, "Escribe el tamaño de las CELDAS (Cola): ");
        obj = new PrioridadBicola(Integer.parseInt(tamano));
        lblMensaje.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnInsertarPorIni = new javax.swing.JButton();
        btnEliminarPorFin = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        PaneVector = new javax.swing.JTextPane();
        lblMensaje = new javax.swing.JLabel();
        txtDato = new javax.swing.JTextField();
        btnInsertar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        comboPrioridad = new javax.swing.JComboBox<>();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel3.setText("Dato:");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 153, 0));
        jLabel1.setText("Cola Prioridad Bicola");

        btnInsertarPorIni.setText("Insertar por Ini");
        btnInsertarPorIni.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarPorIniMouseClicked(evt);
            }
        });
        btnInsertarPorIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertarPorIniActionPerformed(evt);
            }
        });

        btnEliminarPorFin.setText("Eliminar por Fin");
        btnEliminarPorFin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarPorFinMouseClicked(evt);
            }
        });

        jScrollPane1.setViewportView(PaneVector);

        lblMensaje.setFont(new java.awt.Font("Lucida Grande", 2, 16)); // NOI18N
        lblMensaje.setForeground(new java.awt.Color(255, 51, 51));
        lblMensaje.setText("Mensaje");

        btnInsertar.setText("Insertar");
        btnInsertar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnInsertarMouseClicked(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEliminarMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 1, 15)); // NOI18N
        jLabel4.setText("Nivel de prioridad:");

        comboPrioridad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Prioridad", "1", "2", "3" }));

        btnSalir.setText("Salir");
        btnSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSalirMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblMensaje, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalir))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(comboPrioridad, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminarPorFin, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtDato, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(btnInsertarPorIni, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnInsertar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 451, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(191, 191, 191))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel4)
                        .addGap(11, 11, 11)
                        .addComponent(comboPrioridad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnInsertar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnInsertarPorIni)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEliminarPorFin))
                    .addComponent(jScrollPane1))
                .addGap(18, 20, Short.MAX_VALUE)
                .addComponent(lblMensaje)
                .addGap(28, 28, 28))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSalir)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnInsertarPorIniMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarPorIniMouseClicked
        String mensaje = "¡ELIJA UN NIVEL DE PRIORIDAD!";
        if(comboPrioridad.getSelectedIndex() == 0){
            lblMensaje.setText(mensaje);
            return;
        }
        
        if(!obj.insertarPorIniBicola(txtDato.getText().charAt(0),
                comboPrioridad.getSelectedIndex())){
            mensaje = "¡COLA LLENA POR INI!";
            lblMensaje.setText(mensaje);
        }else{
            mensaje = "¡SE INSERTÓ CORRECTAMENTE";
            lblMensaje.setText(mensaje);
        }
        txtDato.setText("");
        mostrarCola();
    }//GEN-LAST:event_btnInsertarPorIniMouseClicked

    private void btnInsertarPorIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertarPorIniActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnInsertarPorIniActionPerformed

    private void btnEliminarPorFinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarPorFinMouseClicked
        String mensaje = "¡COLA VACÍA!";
        if(!obj.eliminarPorFinBicola()){
            lblMensaje.setText(mensaje);
            return;
        }else{
            mensaje = "¡SE ELIMINÓ CORRECTAMENTE!";
            lblMensaje.setText(mensaje);
        }
        mostrarCola();
    }//GEN-LAST:event_btnEliminarPorFinMouseClicked

    private void btnInsertarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnInsertarMouseClicked
        String mensaje = "¡ELIJA UN NIVEL DE PRIORIDAD!";
        if(comboPrioridad.getSelectedIndex() == 0){
            lblMensaje.setText(mensaje);
            return;
        }
        
        if(!obj.insertar(txtDato.getText().charAt(0),
                comboPrioridad.getSelectedIndex())){
            mensaje = "¡COLA LLENA!";
            lblMensaje.setText(mensaje);
        }else{
            mensaje = "¡SE INSERTÓ CORRECTAMENTE";
            lblMensaje.setText(mensaje);
        }
        txtDato.setText("");
        mostrarCola();
    }//GEN-LAST:event_btnInsertarMouseClicked

    private void btnEliminarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEliminarMouseClicked
        String mensaje = "¡COLA VACÍA!";
        if(!obj.eliminar()){
            lblMensaje.setText(mensaje);
            return;
        }else{
            mensaje = "¡SE ELIMINÓ CORRECTAMENTE!";
            lblMensaje.setText(mensaje);
        }
        mostrarCola();
    }//GEN-LAST:event_btnEliminarMouseClicked

    private void btnSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalirMouseClicked
       int exit=JOptionPane.showConfirmDialog(null, "¿Está seguro que desea salir?");
       if(exit==0){
            JOptionPane.showMessageDialog(null, "¡Gracias!");
        System.exit(0);
        }
    }//GEN-LAST:event_btnSalirMouseClicked

   private void mostrarCola() {
        setTitle("VALORES DE INI: " + obj.getIni() + " FIN: " + obj.getFin());
        String cad = "";
        if (obj.getIni() == -1) {
            PaneVector.setText("");
            return;
        }
        for (int i = obj.getIni(); i <=obj.getFin(); i++) {
            cad += String.format("[%d] = [%s] ", i, obj.getValor(i));
        }

        PaneVector.setText(cad);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextPane PaneVector;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnEliminarPorFin;
    private javax.swing.JButton btnInsertar;
    private javax.swing.JButton btnInsertarPorIni;
    private javax.swing.JButton btnSalir;
    private javax.swing.JComboBox<String> comboPrioridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMensaje;
    private javax.swing.JTextField txtDato;
    // End of variables declaration//GEN-END:variables
}
